name: ci

on: push

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            ${{ runner.os }}-
      - run: npm install
      - run: npm run build -- --output-public-path "/${GITHUB_REF#refs/heads/}/"
      - run: npm run compile
      - run: tar cf public.tar public
      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: public.tar

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            ${{ runner.os }}-
      - run: npm install
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, compile]
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/download-artifact@v2
        with:
          name: public
      - run: tar xf public.tar
      - run: aws s3 sync public "s3://triangle.ziorobo.co/${GITHUB_REF#refs/heads/}" --delete
      - run: |
          aws cloudfront wait invalidation-completed \
            --id "$(aws cloudfront create-invalidation --paths '/*' --distribution-id E3C5XFZ2ZBP6PG | jq -r .Invalidation.Id)" \
            --distribution-id E3C5XFZ2ZBP6PG

  test:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            ${{ runner.os }}-
      - uses: microsoft/playwright-github-action@v1
      - run: npm install
      - run: TEST_URL="https://triangle.ziorobo.co/${GITHUB_REF#refs/heads/}/" npm run test
